### ISSUE TITLE
Malware detected your exe

### ISSUE THREAD

**Issue by Celuni** [ph5x5/albion-minimap-overlay#4] opened 2019-05-30 13:15 UTC
Compiled exe detected as malware, please fix.

**Comment by ph5x5** [comment] 2019-06-02 19:40
Could you provide the detection screenshot please? I'll check on my side.

**Comment by ph5x5** [comment] 2019-06-19 08:34
Duplicate of https://github.com/ph5x5/albion-minimap-overlay/issues/5

**Closed as completed by ph5x5** 2019-06-19 08:34 UTC
Labels: duplicate, wontfix
